### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by Linerly** [MediaPlay-Discord/metaverse#1]
# Export automatically for
- [ ] The Web (host it later by using GitHub Pages—performance might be horrible for most, if not all, users)
- [ ] Windows
- [ ] macOS
- [ ] GNU/Linux (it did export, but crashed upon executing it due to missing assets)
- [ ] Android (haven't tried exporting due to the missing Android SDK on my machine, will try to set up in GitHub Actions)
- [ ] iOS (nope, never, unless if someone knows how to handle that or if you can export it yourself for iOS and sideload apps which Apple just)

# Other things to do
- [ ] Set up GitHub Actions/Pages somehow to host the exported HTML5 version of MediaPlay Metaverse
- [ ] Implement internationalization (Godot supports CSV and Weblate supports CSV as well, as it's the easiest format to work with)
- [ ] Set up Weblate to let translators translate MediaPlay Metaverse easily, rather than having to edit the files manually
